### ISSUE TITLE
Black screen after AXK packet

### ISSUE THREAD

**Issue by Biskwit** [Fudjia/RetroSniffer#2]
Hi, i've black screen after received AXK packet, is it normal ?

**Comment by Fudjia** [comment]
Hey, this is normal, if I remember correctly, the client has to connect to the game server and therefore has to open a new socket connection and close the previous one. 
Feel free to make a pull request with these additions.

**Comment by Biskwit** [comment]
Ah okok my bad, thank you very much 👍
